language: node_js
node_js:
  - "node"
  - "8"
  - "7"
  - "6"
env:
  - MONGOOSE_VERSION=4.11.8 STREAM_URL='https://key:secret@us-east.getstream.io/?app_id=42'
matrix:
  include:
    - node_js: 8
      env: MONGOOSE_VERSION=4.0
before_script:
  - npm install mongoose@$MONGOOSE_VERSION
script:
  - bash ./bin/travis.sh
services:
  - mongodb
